### ISSUE TITLE
docker-compose local development

### ISSUE THREAD

**Issue by benkaiser** [Neutron-Creative/Singlelink#180] opened 2021-07-18 11:27 UTC
I can see from the development section there are instructions for setting up the application directly on a machine, but is there support for using docker-compose to setup a server easily on a dev machine?

Specifically I found I needed several changes to try and get docker-compose working properly, see this commit here:
https://github.com/benkaiser/Singlelink/commit/dc6bf316aac0869e42a06fe549ef2aef9a27caa2

And even after all that, I had to provide separate API_URLs to the client for build vs. runtime, because the generated scripts are accessed from the host, wheras the backend-code is executed within the container.

I also found that when trying to start using the dashboard, the preview was rendering a 404, I'm sure I probably set something wrong somewhere, but the client/editor/frontend didn't seem to be able to pull the preview from the API server.
![image](https://user-images.githubusercontent.com/608054/126065218-138d77b3-7e57-4acf-ae6f-88f2072072b2.png)

```
singlelink-editor_1  | Error getting profile
singlelink-editor_1  | Request failed with status code 400
singlelink-editor_1  |
singlelink-editor_1  |   at createError (node_modules/axios/lib/core/createError.js:16:15)
singlelink-editor_1  |   at settle (node_modules/axios/lib/core/settle.js:17:12)
singlelink-editor_1  |   at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:244:11)
singlelink-editor_1  |   at IncomingMessage.emit (events.js:327:22)
singlelink-editor_1  |   at IncomingMessage.EventEmitter.emit (domain.js:486:12)
singlelink-editor_1  |   at endReadableNT (_stream_readable.js:1327:12)
singlelink-editor_1  |   at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Is there any plans to make a clone + docker-compose a supported way to get up and running with development? Or is it purely intended for use when running a production instance on a server?

**Comment by benkaiser** [comment] 2021-07-18 11:28
(when I get some more time through the week, I'll go through the steps of setting them up on a host directly to see if those steps work for me, I just got really caught-up trying to get docker-compose working)

**Comment by NavidK0** [comment] 2021-07-18 11:37
Yeah, apologies for that. v2's docker-compose is not very user-friendly, and it was something that I personally used for testing docker files so we could set it up with Kubernetes. That is why it is set up for a production instance.

I believe v3's process is a lot better, and we now include .env templates that can be used to set up developer instances much easier. See branch here: [Beta v3 Branch](https://github.com/Neutron-Creative/Singlelink/tree/beta-v3)

> Is there any plans to make a clone + docker-compose a supported way to get up and running with development? Or is it purely intended for use when running a production instance on a server?

Yes, absolutely! The latest version definitely makes it easier though. I will note that the docker-compose **does not** include PostgreSQL because it's expected that the user has their own PostgreSQL server already. Though we can include a docker-compose file that has a PostgreSQL setup for people who don't have one.

**Comment by benkaiser** [comment] 2021-07-21 13:26
@NavidK0 the next issue I ran into trying to use docker-compose on beta-v3 is this:

![image](https://user-images.githubusercontent.com/608054/126495833-c6adbe9a-ad7c-4e5d-bcab-13b4d52c5cd2.png)

Do I need to copy config.template.json to clear the s3 bucket config?

**Comment by NavidK0** [comment] 2021-07-21 16:33
@benkaiser Environment vars should definitely override config values, so no you shouldn't need to. Make sure for the docker-compose that you are copying the .env templates and renaming them to the equivalent versions without ".template" in the filename.

So api-config.template.env -> api-config.env
while making sure the necessary vars are filled out.

**Comment by NavidK0** [comment] 2021-07-21 16:38
Another thing to keep in mind is that the readme documentation is woefully outdated. A **lot** of the documentation is meant for Singlelink v2 (or even v1), and we never got around to updating it. So that means if you were following the documentation exactly, there's a good chance that they were meant for an older version of Singlelink.

**Comment by NavidK0** [comment] 2021-07-21 16:57
Let me see if I can run through it on a different computer real quick and reproduce the issue. It'll be on Windows 10 with a fresh docker install.

**Comment by NavidK0** [comment] 2021-07-21 17:54
@benkaiser Alright, so I was able to get it working, but the actual process of building the images takes some time. Additional documentation will definitely help here as well, especially with filling out config values (there are some comments, but more could help).

Here are my steps:

1) `git clone https://github.com/Neutron-Creative/Singlelink.git`
2) `git checkout beta-v3`
3) Copy the template files and remove the ".template" from the filenames.
4) Fill out the values within the template files for api-config.env, editor-config.env, and renderer-config.env.
5) `docker-compose up`

It worked fine for me then. One thing to note is that the image on DockerHub is NOT updated with beta-v3, so building the image is necessary (should happen automatically anyways).

**Comment by jimmybisenius** [comment] 2022-02-13 14:17
I hate to do this to you again Ben...... but..... closing for v4 😅 

please don't hate me

**Closed by jimmybisenius** 2022-02-13 14:17 UTC
Labels: documentation

**Comment by benkaiser** [comment] 2022-02-13 23:19
All good, no hard feelings here @jimmybisenius ! If I pick up singlelink dev again in the future I'll bump the threads that still need fixing.
